baseURL: "http://localhost"
title: "blog.loholt.io"
theme: loveit

languageCode: en
languageName: English

author:
  name: Andreas Loholt
  email: 'andreas.loholt@gmail.com'
  link: 'https://blog.loholt.io'

markup:
  highlight:
    noClasses: false

menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
    - weight: 2
      identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
    - weight: 3
      identifier: about
      pre: ''
      post: ''
      name: About
      url: /about/
      title: ''

params:
  defaultTheme: dark
  gitRepo: ''
  fingerprint: ''
  dateFormat: '02-01-2006'
  title: "blog.loholt.io"
  description: blog.loholt.io
  images:
    - /static/kubernetes.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
        #logo: '/images/kubernetes.png'
      name: blog.loholt.io
      pre: ''
      post: ''
      typeit: true
  footer:
    enable: true
    custom: ''
    hugo: false
    copyright: true
    author: true
    since: 2022
    icp: ''
    license: >-
      <a rel="license external nofollow noopener noreffer"
      href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
      BY-NC 4.0</a>
  section:
    paginate: 20
    dateFormat: 02-01
    rss: 10
  list:
    paginate: 20
    dateFormat: 02-01
    rss: 10
  app:
    title: blog.loholt.io
    noFavicon: false
    svgFavicon: ''
    themeColor: '#ffffff'
    iconColor: '#5bbad5'
    tileColor: '#da532c'
  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: ''
      appID: ''
      searchKey: ''
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: ''
      avatarURL: /images/loholt-andreas.png
      title: 'Andreas Loholt'
      subtitle: Writing about The Cloud Native Ecosystem
      typeit: true
      social: true
      disclaimer: '...mostly stuff relatet to Kubernetes and Conatiner technology' 
    posts:
      enable: true
      paginate: 6
      defaultHiddenFromHomePage: false
  social:
    GitHub: andloh
    Linkedin: 'andreas-loholt-503055145'
    #Lastfm: 'annjlo'
    Email: andreas.loholt@gmail.com
    RSS: true
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: false
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      keepStatic: false
      auto: true
    math:
      enable: true
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      copyTex: true
      mhchem: true
    code:
      copy: true
      maxShownLines: 50
    mapbox:
      accessToken: ''
      lightStyle: 'mapbox://styles/mapbox/light-v10?optimize=true'
      darkStyle: 'mapbox://styles/mapbox/dark-v10?optimize=true'
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
    share:
      enable: true
      Twitter: true
      Facebook: false
      Linkedin: true
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: true
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: false
      Instapaper: false
      Pocket: false
      Flipboard: false
      Weibo: false
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      disqus:
        enable: false
        shortname: ''
      gitalk:
        enable: false
        owner: ''
        repo: ''
        clientId: ''
        clientSecret: ''
      valine:
        enable: false
        appId: ''
        appKey: ''
        placeholder: ''
        avatar: mp
        meta: ''
        pageSize: 10
        lang: ''
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: ''
        emoji: ''
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ''
        languageCode: ''
      telegram:
        enable: false
        siteID: ''
        limit: 5
        height: ''
        color: ''
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: false
        repo: ''
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        darkTheme: github-dark
    library:
      css: {}
      js: {}
    seo:
      images: []
      publisher:
        name: ''
        logoUrl: ''
  typeit:
    speed: 70
    cursorSpeed: 10000
    cursorChar: '|'
    duration: -1
  verification:
    google: ''
    bing: ''
    yandex: ''
    pinterest: ''
    baidu: ''
  seo:
    image: ''
    thumbnailUrl: ''
  analytics:
    enable: true
    google:
      id: 'G-K43NGWG8SP'
      anonymizeIP: true
    fathom:
      id: ''
      server: ''
  cookieconsent:
    enable: true
    content:
      message: ''
      dismiss: ''
      link: ''
  cdn:
    data: ''
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: ':filename'
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
